upstream ministry_api {
  server api:4000;
  keepalive 32;
}

upstream ministry_websocket {
  server websocket:4100;
  keepalive 16;
}

upstream ministry_admin {
  server admin-web:3001;
  keepalive 16;
}
