ALTER TABLE "Clip"
  ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'GENERAL',
  ADD COLUMN IF NOT EXISTS "durationSeconds" INTEGER,
  ADD COLUMN IF NOT EXISTS "speaker" TEXT,
  ADD COLUMN IF NOT EXISTS "scriptureReferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "viewCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "Clip_category_idx" ON "Clip"("category");
CREATE INDEX IF NOT EXISTS "Clip_featured_idx" ON "Clip"("featured");
CREATE INDEX IF NOT EXISTS "Clip_publishedAt_idx" ON "Clip"("publishedAt");
